#!/usr/bin/env bash
# Displays contents of the current directoory in list format.
# only displays the part of the name after the first dash.

llist=$(ls)
for i in $list; do
	echo "$i" | cut -d '-' -f2
done
